import { StyleSheet } from "react-native";
import { Colors } from "./global";

export const styles = StyleSheet.create({
	allChicksContainer: {
		justifyContent: "center",
		alignItems: "center",
		flexDirection: "row",
		flexWrap: "wrap",
		gap: 20,
	},
	allChicksTitle: {
		fontSize: 32,
		textAlign: "center",
		marginTop: 50,
	},
	allChicksHeader: {
		gap: 30,
		marginBottom: 50,
	},

	chickenContainer: {
		borderColor: Colors.primary,
		borderWidth: 2,
		borderRadius: 15,
		marginTop: 25,
		paddingHorizontal: 15,
		width: 160,
		aspectRatio: 1,
		backgroundColor: Colors.secondary,
		justifyContent: "center",
		shadowColor: "#000",
		shadowOffset: { width: 4, height: 4 },
		shadowOpacity: 0.95,
		shadowRadius: 3.84,
		elevation: 3,
	},
	chickenText: {
		fontWeight: "600",
	},
	chickenImageContainer: {
		position: "absolute",
		borderRadius: 40,
		transform: [{ translateX: 40 }, { translateY: -80 }],
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.23,
		shadowRadius: 2.62,
		elevation: 2,
	},
	chickenImage: {
		backgroundColor: Colors.secondary,
		borderColor: Colors.yellow,
		borderWidth: 2,
		borderRadius: 40,
		width: 80,
		aspectRatio: 1,
	},
	closeButtonContainer: {
		position: "absolute",
		right: -10,
		top: -10,
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 2,
		backgroundColor: Colors.red,
		borderRadius: 20,
		width: 20,
		aspectRatio: 1,
		alignItems: "center",
	},
	addChickenContainer: {
		width: "80%",
		height: "70%",
		alignSelf: "center",
		alignItems: "center",
		padding: 20,
		margin: "auto",
		backgroundColor: Colors.secondary,
		borderRadius: 20,
		shadowOffset: { width: 0, height: 5 },
		shadowOpacity: 0.34,
		shadowRadius: 6.27,
		elevation: 4,
		gap: 40,
	},
	addChickenImage: {
		height: 150,
		width: 150,
		borderColor: Colors.primary,
		borderWidth: 3,
		borderRadius: 100,
		marginBottom: 30,
	},
	addChickenTextInput: {
		height: 50,
		width: "80%",
		borderWidth: 1,
		borderColor: Colors.shadows,
		marginHorizontal: 20,
		borderRadius: 25,
		paddingLeft: 10,
	},
});
